name: "${APPLICATION_NAME}"
services:
# PostgresSQL database service
  postgres:
    image: "postgres:17"
    container_name: "db"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Links internal DB folder to a named volume
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
# Spring Boot backend service
  backend:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: "backend"
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    environment:
      # This overrides the application.properties value ONLY inside Docker
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
    depends_on:
      postgres:
        condition: service_healthy
# Persistent volume for database data
volumes:
  postgres_data:

