spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/cyclerouteplanner}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

osm:
  overpass:
    base-url: ${OSM_OVERPASS_BASE_URL:https://overpass-api.de/api}
