spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cyclerouteplanner}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:postgres}}

logging:
  level:
    org.springframework.boot.docker.compose.core.DockerCli: WARN

osm:
  overpass:
    base-url: ${OSM_OVERPASS_BASE_URL:https://overpass-api.de/api}
