#!/bin/sh
#
# Rebuild BRouter .rd5 segments from a base OSM PBF while injecting
# pseudo-tags generated by the backend from geo.routing_edge_cache.
#
# Expected mounted paths in the container:
#   /planet       -> base OSM PBF extracts
#   /build-input  -> db_tags.csv.gz exported by backend
#   /segments     -> output .rd5 files
#   /srtm1_bef    -> optional 1" elevation tiles (.bef)
#   /srtm3_bef    -> optional 3" elevation tiles (.bef)
#
# Typical usage:
#   docker compose run --rm --entrypoint /usr/local/bin/build-segments-with-pseudotags.sh \
#     -e PLANET_FILE=/planet/estonia-latest.osm.pbf \
#     brouter
set -eu

BROUTER_HOME="${BROUTER_HOME:-/opt/brouter}"
PLANET_FILE="${PLANET_FILE:-/planet/estonia-latest.osm.pbf}"
PLANET_AUTO_DOWNLOAD="${PLANET_AUTO_DOWNLOAD:-true}"
PLANET_DOWNLOAD_URL="${PLANET_DOWNLOAD_URL:-https://download.geofabrik.de/europe/estonia-latest.osm.pbf}"
PSEUDO_TAGS_FILE="${PSEUDO_TAGS_FILE:-/build-input/db_tags.csv.gz}"
OUTPUT_SEGMENTS_DIR="${OUTPUT_SEGMENTS_DIR:-/segments}"
WORK_DIR="${WORK_DIR:-/tmp/brouter-mapcreation}"
SRTM1_DIR="${SRTM1_DIR:-/srtm1_bef}"
SRTM3_DIR="${SRTM3_DIR:-/srtm3_bef}"
JAVA_MAPCREATOR_OPTS="${JAVA_MAPCREATOR_OPTS:--Xmx4096M -Xms4096M -Xmn256M}"

LOOKUPS_FILE="${LOOKUPS_FILE:-${BROUTER_HOME}/profiles2/lookups.dat}"
PROFILE_ALL="${PROFILE_ALL:-${BROUTER_HOME}/profiles2/all.brf}"
PROFILE_TREKKING="${PROFILE_TREKKING:-${BROUTER_HOME}/profiles2/trekking.brf}"
PROFILE_SOFTACCESS="${PROFILE_SOFTACCESS:-${BROUTER_HOME}/profiles2/softaccess.brf}"
BROUTER_JAR="${BROUTER_JAR:-${BROUTER_HOME}/brouter.jar}"

is_true() {
  case "$1" in
    true|TRUE|True|1|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

if [ ! -f "${PLANET_FILE}" ]; then
  if is_true "${PLANET_AUTO_DOWNLOAD}"; then
    if [ -z "${PLANET_DOWNLOAD_URL}" ]; then
      echo "[segment-build] ERROR: PLANET_FILE missing and PLANET_DOWNLOAD_URL is empty" >&2
      exit 1
    fi
    if ! command -v curl >/dev/null 2>&1; then
      echo "[segment-build] ERROR: PLANET_FILE missing and curl is not available for auto-download" >&2
      exit 1
    fi

    PLANET_DIR="$(dirname "${PLANET_FILE}")"
    PLANET_TMP_FILE="${PLANET_FILE}.download"
    mkdir -p "${PLANET_DIR}"

    echo "[segment-build] PLANET_FILE not found, downloading from ${PLANET_DOWNLOAD_URL}"
    if ! curl -fL --retry 3 --retry-delay 2 -o "${PLANET_TMP_FILE}" "${PLANET_DOWNLOAD_URL}"; then
      rm -f "${PLANET_TMP_FILE}"
      echo "[segment-build] ERROR: failed to download PLANET_FILE from ${PLANET_DOWNLOAD_URL}" >&2
      exit 1
    fi
    mv -f "${PLANET_TMP_FILE}" "${PLANET_FILE}"
    echo "[segment-build] downloaded PLANET_FILE to ${PLANET_FILE}"
  else
    echo "[segment-build] ERROR: PLANET_FILE not found: ${PLANET_FILE}" >&2
    echo "[segment-build] Set PLANET_AUTO_DOWNLOAD=true or provide PLANET_FILE manually." >&2
    exit 1
  fi
fi
if [ ! -f "${PSEUDO_TAGS_FILE}" ]; then
  echo "[segment-build] ERROR: PSEUDO_TAGS_FILE not found: ${PSEUDO_TAGS_FILE}" >&2
  exit 1
fi
if [ ! -f "${LOOKUPS_FILE}" ] || [ ! -f "${PROFILE_ALL}" ] || [ ! -f "${PROFILE_TREKKING}" ] || [ ! -f "${PROFILE_SOFTACCESS}" ]; then
  echo "[segment-build] ERROR: required lookup/profile files not found under ${BROUTER_HOME}/profiles2" >&2
  exit 1
fi
if [ ! -f "${BROUTER_JAR}" ]; then
  echo "[segment-build] ERROR: BRouter jar not found: ${BROUTER_JAR}" >&2
  exit 1
fi

mkdir -p "${WORK_DIR}" "${OUTPUT_SEGMENTS_DIR}"
rm -rf "${WORK_DIR}/nodetiles" "${WORK_DIR}/waytiles" "${WORK_DIR}/waytiles55" \
       "${WORK_DIR}/nodes55" "${WORK_DIR}/unodes55" "${WORK_DIR}/segments"
mkdir -p "${WORK_DIR}/nodetiles" "${WORK_DIR}/waytiles" "${WORK_DIR}/waytiles55" "${WORK_DIR}/nodes55"

echo "[segment-build] running OsmFastCutter with pseudo tags: ${PSEUDO_TAGS_FILE}"
java ${JAVA_MAPCREATOR_OPTS} \
  -cp "${BROUTER_JAR}" \
  -Ddeletetmpfiles=true -DuseDenseMaps=true \
  btools.util.StackSampler btools.mapcreator.OsmFastCutter \
  "${LOOKUPS_FILE}" \
  "${WORK_DIR}/nodetiles" \
  "${WORK_DIR}/waytiles" \
  "${WORK_DIR}/nodes55" \
  "${WORK_DIR}/waytiles55" \
  "${WORK_DIR}/bordernids.dat" \
  "${WORK_DIR}/relations.dat" \
  "${WORK_DIR}/restrictions.dat" \
  "${PROFILE_ALL}" \
  "${PROFILE_TREKKING}" \
  "${PROFILE_SOFTACCESS}" \
  "${PLANET_FILE}" \
  "${PSEUDO_TAGS_FILE}"

mkdir -p "${WORK_DIR}/unodes55"

SRTM_ARGS=""
if [ -d "${SRTM1_DIR}" ] && [ "$(find "${SRTM1_DIR}" -type f 2>/dev/null | wc -l)" -gt 0 ] && \
   [ -d "${SRTM3_DIR}" ] && [ "$(find "${SRTM3_DIR}" -type f 2>/dev/null | wc -l)" -gt 0 ]; then
  SRTM_ARGS="${SRTM1_DIR} ${SRTM3_DIR}"
elif [ -d "${SRTM3_DIR}" ] && [ "$(find "${SRTM3_DIR}" -type f 2>/dev/null | wc -l)" -gt 0 ]; then
  SRTM_ARGS="${SRTM3_DIR}"
elif [ -d "${SRTM1_DIR}" ] && [ "$(find "${SRTM1_DIR}" -type f 2>/dev/null | wc -l)" -gt 0 ]; then
  SRTM_ARGS="${SRTM1_DIR}"
else
  mkdir -p "${WORK_DIR}/empty_srtm"
  SRTM_ARGS="${WORK_DIR}/empty_srtm"
fi

echo "[segment-build] running PosUnifier with SRTM args: ${SRTM_ARGS}"
# shellcheck disable=SC2086
java ${JAVA_MAPCREATOR_OPTS} \
  -cp "${BROUTER_JAR}" \
  -Ddeletetmpfiles=true -DuseDenseMaps=true \
  btools.util.StackSampler btools.mapcreator.PosUnifier \
  "${WORK_DIR}/nodes55" \
  "${WORK_DIR}/unodes55" \
  "${WORK_DIR}/bordernids.dat" \
  "${WORK_DIR}/bordernodes.dat" \
  ${SRTM_ARGS}

mkdir -p "${WORK_DIR}/segments"
echo "[segment-build] running WayLinker"
java ${JAVA_MAPCREATOR_OPTS} \
  -cp "${BROUTER_JAR}" \
  -DuseDenseMaps=true -DskipEncodingCheck=true \
  btools.util.StackSampler btools.mapcreator.WayLinker \
  "${WORK_DIR}/unodes55" \
  "${WORK_DIR}/waytiles55" \
  "${WORK_DIR}/bordernodes.dat" \
  "${WORK_DIR}/restrictions.dat" \
  "${LOOKUPS_FILE}" \
  "${PROFILE_ALL}" \
  "${WORK_DIR}/segments" \
  rd5

if ! ls "${WORK_DIR}/segments"/*.rd5 >/dev/null 2>&1; then
  echo "[segment-build] ERROR: no .rd5 files produced" >&2
  exit 1
fi

cp -f "${WORK_DIR}/segments"/*.rd5 "${OUTPUT_SEGMENTS_DIR}/"
echo "[segment-build] copied $(ls "${WORK_DIR}/segments"/*.rd5 | wc -l | tr -d ' ') segments to ${OUTPUT_SEGMENTS_DIR}"
echo "[segment-build] done"
